version: '3.7'
services:
   flower:
      build: 
         context: .
         dockerfile: images/flower_container
      container_name: "flower"
      environment:
         - NODE_ENV=development
         - FOO=bar
      volumes:
         - .:/usr/src/app
      ports:
         - 3000:3000
      links:
         - mongodb
      depends_on:
         - mongodb
   mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
         - MONGO_DATA_DIR=/data/db
         - MONGO_LOG_DIR=/dev/null
      volumes:
         - ./data/db:/data/db
      ports:
         - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
   ws:
      build: 
         context: .
         dockerfile: images/services_container
      links:
         - mongodb
      ports:
         - 5000:5000
      depends_on:
         - mongodb

